list: $/martinimultimedia/table/models/user/columns.yaml
modelClass: EugeneTolok\Telegram\Models\User
title: User
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
recordsPerPage: 20
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'martinimultimedia/table/user/update/:id'
